name: Build

on:
  push:
    branches: [ v6 ]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Clone
        run: |
          git clone --branch v6 https://github.com/Dot-lua/TypeWriter/ ./
          ls

      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: |
          cd ./TypeWriter
          npm i
          npm i -g pkg
          cd ..

      - name: Build
        run: |
          chmod +x ./Build.sh
          ./Build.sh
          ls

      - uses: actions/upload-artifact@v3
        with:
          name: typewriter-alpine-arm64
          path: ./.build/typewriter-alpine-arm64

      - uses: actions/upload-artifact@v3
        with:
          name: typewriter-alpine-x64
          path: ./.build/typewriter-alpine-x64

      - uses: actions/upload-artifact@v3
        with:
          name: typewriter-linux-arm64
          path: ./.build/typewriter-linux-arm64

      - uses: actions/upload-artifact@v3
        with:
          name: typewriter-linux-x64
          path: ./.build/typewriter-linux-x64

      - uses: actions/upload-artifact@v3
        with:
          name: typewriter-linuxstatic-arm64
          path: ./.build/typewriter-linuxstatic-arm64

      - uses: actions/upload-artifact@v3
        with:
          name: typewriter-linuxstatic-x64
          path: ./.build/typewriter-linuxstatic-x64

      - uses: actions/upload-artifact@v3
        with:
          name: typewriter-macos-arm64
          path: ./.build/typewriter-macos-arm64

      - uses: actions/upload-artifact@v3
        with:
          name: typewriter-macos-x64
          path: ./.build/typewriter-macos-x64

      - uses: actions/upload-artifact@v3
        with:
          name: typewriter-win-arm64
          path: ./.build/typewriter-win-arm64.exe

      - uses: actions/upload-artifact@v3
        with:
          name: typewriter-win-x64
          path: ./.build/typewriter-win-x64.exe