name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  workflow_call:

jobs:
  Windows-Build:
    runs-on: windows-latest
    steps:
      - name: Clone
        run: |
          git clone https://github.com/Dot-lua/TypeWriter/ ./
          ls
          pwd

      - name: Download luvit
        working-directory: ./TypeWriter4.0/
        run: |
          mkdir ./Binary/
          cd ./Binary/
          curl -L --output ./luvit.zip --url https://github.com/truemedian/luvit-bin/releases/latest/download/luvit-bin-Windows-x86_64.zip
          tar -xf ./luvit.zip -C ./
          
      - name: Install TypeWriter Deps
        working-directory: ./TypeWriter4.0/TypeWriter/
        run: |
          ../Binary/lit install
          ls
          
      - name: Install Executable deps
        working-directory: ./TypeWriter4.0/TypeWriter/Assets/ExecutableProject/
        run: ../../../Binary/lit install
      
      - name: Build TypeWriter
        working-directory: ./TypeWriter4.0/
        run: ./Binary/luvi ./TypeWriter -o ./TypeWriter.exe
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: Windows
          path: ./TypeWriter4.0/TypeWriter.exe
          
  Mac-Build:
    runs-on: macos-latest
    steps:
      - name: Clone
        run: |
          git clone https://github.com/Dot-lua/TypeWriter/ ./
          ls
          pwd

      - name: Download luvit
        working-directory: ./TypeWriter4.0/
        run: |
          mkdir ./Binary/
          cd ./Binary/
          curl -L --output ./luvit.zip --url https://github.com/truemedian/luvit-bin/releases/latest/download/luvit-bin-Darwin-x86_64.tar.gz
          tar -xf ./luvit.zip -C ./
          
      - name: Install TypeWriter Deps
        working-directory: ./TypeWriter4.0/TypeWriter/
        run: for i in {1..5}; do timeout 10 ../Binary/lit install && break || sleep 15; done
          
      - name: Install Executable deps
        working-directory: ./TypeWriter4.0/TypeWriter/Assets/ExecutableProject/
        run: for i in {1..5}; do timeout 10 ../../../Binary/lit install && break || sleep 15; done
      
      - name: Build TypeWriter
        working-directory: ./TypeWriter4.0/
        run: ./Binary/luvi ./TypeWriter -o ../TypeWriter
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: MacOs
          path: ./TypeWriter
