name: Build

on:
  push:
    branches: [ v6 ]
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Clone
        run: |
          git clone --branch v6 https://github.com/Dot-lua/TypeWriter/ ./
          ls

      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: |
          cd ./TypeWriter
          npm i
          npm i -g pkg
          cd ..

      - name: Build
        run: |
          chmod +x ./Build.sh
          ./Build.sh
          ls

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./.build/