name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Windows-Build:
    runs-on: windows-latest
    steps:
      - name: Clone
        run: |
          git clone https://github.com/Dot-lua/TypeWriter/ ./
          ls
          pwd

      - name: Download luvit
        working-directory: ./TypeWriter4.0/
        run: |
          mkdir ./Binary/
          cd ./Binary/
          curl --output ./luvit.zip --url https://github.com/truemedian/luvit-bin/releases/latest/download/luvit-bin-Windows-x86_64.zip
          7z x luvit.zip
          ls
