name: NewBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  workflow_call:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        run: |
          git clone https://github.com/Dot-lua/TypeWriter/ ./
          ls

      - name: Download luvit
        working-directory: TypeWriter
        run: |
          mkdir ./Binary/
          cd ./Binary
          curl -fL https://github.com/truemedian/luvit-bin/raw/main/install.sh | sh
          ls
          pwd

      - name: Download Deps
        working-directory: TypeWriter/TypeWriter
        run: |
          function timeout() { perl -e 'alarm shift; exec @ARGV' "$@"; }
          for i in {1..5}; do timeout 10 ../Binary/lit install && break || sleep 15; done
          ls
          pwd

      - name: Install Executable deps
        working-directory: ./TypeWriter/TypeWriter/Assets/ExecutableProject/
        run: |
          function timeout() { perl -e 'alarm shift; exec @ARGV' "$@"; }
          for i in {1..5}; do timeout 10 ../../../Binary/lit install && break || sleep 15; done
          ls
          pwd

      - name: Build TypeWriter
        working-directory: ./TypeWriter/
        run: |
          ./Binary/luvi ./TypeWriter -o ./Binary/TypeWriter
          ls ../

      - name: Set Env var
        run: |
          echo "artifact=TypeWriter-$(uname -s)-$(uname -m)" >> $GITHUB_ENV

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: "${{ env.artifact }}"
          path: ./TypeWriter/Binary/TypeWriter

  darwin:
    runs-on: macos-latest
    steps:
      - name: Clone
        run: |
          git clone https://github.com/Dot-lua/TypeWriter/ ./
          ls

      - name: Download luvit
        working-directory: TypeWriter
        run: |
          mkdir ./Binary/
          cd ./Binary
          curl -fL https://github.com/truemedian/luvit-bin/raw/main/install.sh | sh
          ls
          pwd

      - name: Download Deps
        working-directory: TypeWriter/TypeWriter
        run: |
          function timeout() { perl -e 'alarm shift; exec @ARGV' "$@"; }
          for i in {1..5}; do timeout 10 ../Binary/lit install && break || sleep 15; done
          ls
          pwd

      - name: Install Executable deps
        working-directory: ./TypeWriter/TypeWriter/Assets/ExecutableProject/
        run: |
          function timeout() { perl -e 'alarm shift; exec @ARGV' "$@"; }
          for i in {1..5}; do timeout 10 ../../../Binary/lit install && break || sleep 15; done
          ls
          pwd

      - name: Build TypeWriter
        working-directory: ./TypeWriter/
        run: |
          ./Binary/luvi ./TypeWriter -o ./Binary/TypeWriter
          ls ../

      - name: Set Env var
        run: |
          echo "artifact=TypeWriter-$(uname -s)-$(uname -m)" >> $GITHUB_ENV

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: "${{ env.artifact }}"
          path: ./TypeWriter/Binary/TypeWriter

  windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        arch: [i386, x86_64]
    env:
      BUILD_ARCH: ${{ matrix.arch }}
    steps:
      - name: Clone
        run: |
          git clone https://github.com/Dot-lua/TypeWriter/ ./
          ls
          pwd

      - name: Download luvit
        working-directory: ./TypeWriter/
        run: |
          mkdir ./Binary/
          cd ./Binary/
          curl -L --output ./luvit.zip --url https://github.com/truemedian/luvit-bin/releases/latest/download/luvit-bin-Windows-x86_64.zip
          tar -xf ./luvit.zip -C ./
          
      - name: Install TypeWriter Deps
        working-directory: ./TypeWriter/TypeWriter/
        run: |
          ../Binary/lit install
          ls
          
      - name: Install Executable deps
        working-directory: ./TypeWriter/TypeWriter/Assets/ExecutableProject/
        run: |
          ../../../Binary/lit install
          ls
      
      - name: Build TypeWriter
        working-directory: ./TypeWriter/
        run: ./Binary/luvi ./TypeWriter -o ./TypeWriter.exe
        
      - name: Download resourcehacker
        working-directory: ./TypeWriter/
        run: |
          curl.exe -L --url http://www.angusj.com/resourcehacker/resource_hacker.zip --output ./RH.zip
          tar -xf ./RH.zip
          
      - name: Change icon
        working-directory: ./TypeWriter/
        run: |
          ./ResourceHacker.exe -open ".\TypeWriter.exe" -save ".\TypeWriter.exe" -action addoverwrite -res .\Icon.ico -mask ICONGROUP,MAINICON

      - name: Set env Var
        working-directory: ./TypeWriter/
        run: |
          Write-Output "artifact=TypeWriter-Windows-$env:BUILD_ARCH"  | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: ${{ env.artifact }}
          path: ./TypeWriter/TypeWriter.exe

  linux-arm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [armv6, armv7, aarch64]
    steps:
      - name: Clone
        run: |
          git clone https://github.com/Dot-lua/TypeWriter/ ./
          ls

      - uses: uraimo/run-on-arch-action@v2
        name: Build
        with:
          distro: stretch
          arch: ${{ matrix.arch }}
          githubToken: ${{ github.token }}

          shell: /bin/bash
          install: |
            apt-get update -q -y
            apt-get install -q -y git curl
          run: |
            cd ./TypeWriter/
            mkdir ./Binary/
            cd ./Binary
            curl -fL https://github.com/truemedian/luvit-bin/raw/main/install.sh | sh
            ls
            pwd
            cd ../
            cd ./TypeWriter/
            function timeout() { perl -e 'alarm shift; exec @ARGV' "$@"; }
            for i in {1..5}; do timeout 10 ../Binary/lit install && break || sleep 15; done
            ls
            pwd
            cd ./Assets/ExecutableProject/
            for i in {1..5}; do timeout 10 ../../../Binary/lit install && break || sleep 15; done
            ls
            pwd
            cd ../../../
            ls
            pwd
            ./Binary/luvi ./TypeWriter -o ./Binary/TypeWriter

      - name: Set Env var
        run: |
          echo "artifact=TypeWriter-$(uname -s)-${{ matrix.arch }}" >> $GITHUB_ENV

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: "${{ env.artifact }}"
          path: ./TypeWriter/Binary/TypeWriter