name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Build-Workflow:
    uses: ./.github/workflows/build.yml
    
  Upload-Release-Assets:
    runs-on: windows-latest
    needs: [Build-Workflow]
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
