name: Upload release assets

on:
  release:
    types:
      - created

jobs:
  Build-Workflow:
    uses: ./.github/workflows/build.yml
    
  Upload-Release-Assets:
    runs-on: windows-latest
    needs: [Build-Workflow]
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: ./
    
      - name: List artifacts
        run: |
          ls
          
      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./
