name: Upload release assets

on:
  release:
    types:
      - created

jobs:
  Build-Workflow:
    uses: ./.github/workflows/build.yml
    
  Upload-Release-Assets:
    runs-on: ubuntu-latest
    needs: [Build-Workflow]
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: ./
    
      - name: List artifacts
        run: |
          ls
          
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
      
      - name: Echo url
        run: echo ${{ steps.get_release.outputs.upload_url }}
          
      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./Windows/TypeWriter.exe
